//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyFly.com.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AircraftInfo
    {
        public string AC_ID { get; set; }
        public string AC_Name { get; set; }
        public string FlightID { get; set; }
        public int PassengerCapacity { get; set; }
        public Nullable<int> CargoCapacity { get; set; }
    
        public virtual FlightInfo FlightInfo { get; set; }
    }
}
